language: node_js
node_js:
  - node # uses most recent stable node version
services:
  - postgresql # starts up postgres
addons:
  postgresql: '9.6' # highest available postgres version on Travis
dist: trusty # uses trusty environment
sudo: false # when on trusty, uses Docker containers for speed
notifications:
  email:
    on_success: change # default: change (only when going from broken to fixed)
    on_failure: always # default: always (which is annoying, as it should be)
install:
  - npm ci # faster, goes only from package-lock
before_script:
  - psql -c 'create database "tastygravy-test";' -U postgres # remember to change this name if you change it elsewhere (e.g. package.json)

before_deploy:
  - npm run build-client # make the bundle
  - rm -rf node_modules # omit from the tarball, since we skip cleanup
deploy:
  skip_cleanup: true # prevents travis from deleting the build
  provider: heroku
  app: gravytrainofficial # see README
  api_key:
    secure: Nhr7XetQb+YvtuhXki/u0LgWzzE6tjQOma0hMrg+imd4+ChvKf/d5XVYH9pHmGvcdcC0xIpZWTH1jQA6jIBobiuRQF3UjJF34gc6PlC3lkLMnrqxwrrLgjgAgIK4aUNGTd8a6Tpc63ZOjTliLAnvQdKTSVfDyZ9bOWylyehGQdjCLR0K24L7DxX4IZNQdmQEFjz8tKBFfKFdzsbbWpLRj+iikZAfCzyn8UvmbhDgmdLKQIQekleylqzcFEyqWyEi+bFF8G/nlIWy4R18j2/LdT9noHVI23lYHWQAhyF8IcOHyEkh0R+rUt66Y65Sv9hTHXbBKJjAidQKnTxR1VTNc9fFv+RL5sK58PKSeiCfzHSUcE51boRnNsfBfc2RvegL4Z9oJfoNDdhV+D1pdrhmsXd8dLo/4Ju4DZyfgeo+Fvlv9EbhC1aSWLFm8X8JkFGRDohw+gmh1q37xZFQpXsVesn/zdMVInzIR4GGBxRRZYwK6cVTC9DBd5vUpEsttM4NcDBCAB0WLz/6vLPAlf9KDmepHS28BoLyGhCiBRKUuHe9gigD9IL1CE6MX9K0Ov5jCZxcbZ1IBDoJNbjesJ3HiZz4y2y9Z/i3bUa5vxUQxnZ6vPuae92w1P9uYWvWFShMmnamL/HQph8gIyA7bOMmbqozEhNjIvboIfVhz9ZIiSg= # see README
