language: node_js
node_js:
  - node # uses most recent stable node version
services:
  - postgresql # starts up postgres
addons:
  postgresql: '9.6' # highest available postgres version on Travis
dist: trusty # uses trusty environment
sudo: false # when on trusty, uses Docker containers for speed
notifications:
  email:
    on_success: change # default: change (only when going from broken to fixed)
    on_failure: always # default: always (which is annoying, as it should be)
install:
  - npm ci # faster, goes only from package-lock
before_script:
  - psql -c 'create database "tastygravy-test";' -U postgres # remember to change this name if you change it elsewhere (e.g. package.json)

before_deploy:
  - npm run build-client # make the bundle
  - rm -rf node_modules # omit from the tarball, since we skip cleanup
deploy:
  skip_cleanup: true # prevents travis from deleting the build
  provider: heroku
  app: gravytrainofficial # see README
  api_key:
    secure: iMWGnrwpxXb4h20r632Q5yCWMtuOOVo0RqdjNSi1fone4nh7fW6w0YhrSKCaO4eo4Sdxpv+ozyBFFBnBxVJUSIwn4bCngwUd7T9FVGWHAy08c/XXz8xOj+d+YeNTuKCrewy6xOyKtHwIoiFwY7r7pckWLmgWnyJsas8QtBrLjbGoqXCyK9mnePZJyrd6m6JzQNO2LgwnkjZUpEX7p+M1+lAHlx+9KqyEAXLiY41gLVn6z2I74Lbwh+43vovZdNRBojgpOdOeidoNALHWgp9yQxmQuIyU7xuniH1GrUA/V973OdoP4ESwDx2cnuFETSAX/xT8RiG3mFJUaFJnUhQXiHOt03I1X3VobIq/K/PrMWrKHHyZRmQM/hTBkVIa3Jej75lXWs6HSl1Vc9q58SBHUD/fdL+Ewm44Vh0F1qi2c+yIwk+AF8lU/inRUvDEes/q04U8okad5JRm/CyhHh/2ISfP9TeE3s/MjHRk6zeA+WZ0RAOTQauAz6xTVJE4AYaUkv+cOa3G20v24fsH5tLZdh61y1/WrB4DRSjxFE9CczKg0rg7nCMQpykIwWmxbfF8/vVXQpruN6JlhQ6YuFXpaiss/PHNRsOAtf3sKbUznS7wnplYEw3KkMxg60MkvIyFv9ON+m5x+1jC6rSYp0/+ezZTs8TfR6sHtjYg1rB/Tpg= # see README
